const REQUIRED = [
  'DISCORD_BOT_TOKEN', 'DISCORD_PUBLIC_KEY', 'DISCORD_APP_ID',
  'DISCORD_GUILD_ID', 'DISCORD_MOD_ROLE_ID',
  'ANNOUNCE_CHANNEL_ID', 'LINKS_CHANNEL_ID', 'STATS_CHANNEL_ID', 'SALES_CHANNEL_ID',
  'CRON_SECRET', 'SUPABASE_URL', 'SUPABASE_SERVICE_ROLE_KEY',
]

export function loadConfig(env = process.env) {
  for (const key of REQUIRED) {
    if (!env[key]) throw new Error(`Missing required environment variable: ${key}`)
  }
  return {
    BOT_TOKEN: env.DISCORD_BOT_TOKEN,
    PUBLIC_KEY: env.DISCORD_PUBLIC_KEY,
    APP_ID: env.DISCORD_APP_ID,
    GUILD_ID: env.DISCORD_GUILD_ID,
    MOD_ROLE_ID: env.DISCORD_MOD_ROLE_ID,
    ANNOUNCE_CHANNEL_ID: env.ANNOUNCE_CHANNEL_ID,
    LINKS_CHANNEL_ID: env.LINKS_CHANNEL_ID,
    STATS_CHANNEL_ID: env.STATS_CHANNEL_ID,
    SALES_CHANNEL_ID: env.SALES_CHANNEL_ID,
    CRON_SECRET: env.CRON_SECRET,
    SUPABASE_URL: env.SUPABASE_URL,
    SUPABASE_SERVICE_ROLE_KEY: env.SUPABASE_SERVICE_ROLE_KEY,
    COLLECTION_SYMBOL: env.VITE_COLLECTION_SYMBOL || 'primos',
  }
}
